In [1]:
import cvxpy as cp
import numpy as np

In [2]:
x1, x2 = cp.Variable(), cp.Variable()

obj = cp.Maximize(20*x1 + 60*x2)

cons = [5*x1 + 4*x2 <= 80,
        2*x1 + 4*x2 <= 40,
        2*x1 + 8*x2 <= 64,
        x1 >= 0,
        x2 >=0] 


In [3]:
p = cp.Problem(obj, cons)
p.solve(verbose=True)



ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -4.814e+02  -1.107e+03  +3e+02  2e-04  3e-01  1e+00  5e+01    ---    ---    1  1  - |  -  - 
 1  -5.152e+02  -5.723e+02  +3e+01  2e-05  3e-02  3e-01  5e+00  0.9056  4e-03   0  0  0 |  0  0
 2  -5.199e+02  -5.250e+02  +3e+00  2e-06  3e-03  3e-02  4e-01  0.9101  2e-03   1  0  0 |  0  0
 3  -5.200e+02  -5.201e+02  +3e-02  2e-08  3e-05  4e-04  5e-03  0.9890  1e-04   1  0  0 |  0  0
 4  -5.200e+02  -5.200e+02  +3e-04  2e-10  4e-07  4e-06  5e-05  0.9890  1e-04   1  0  0 |  0  0
 5  -5.200e+02  -5.200e+02  +3e-06  2e-12  4e-09  5e-08  6e-07  0.9890  1e-04   1  0  0 |  0  0

OPTIMAL (within feastol=4.2e-09, reltol=6.7e-09, abstol=3.5e-06).
Runtime: 0.000182 seconds.



519.9999998709314

In [4]:
p

Problem(Maximize(Expression(AFFINE, UNKNOWN, ())), [Inequality(Expression(AFFINE, UNKNOWN, ())), Inequality(Expression(AFFINE, UNKNOWN, ())), Inequality(Expression(AFFINE, UNKNOWN, ())), Inequality(Constant(CONSTANT, ZERO, ())), Inequality(Constant(CONSTANT, ZERO, ()))])

In [5]:
x1.value

array(7.99999999)

In [6]:
x2.value

array(6.)

In [7]:
c = np.array([-20.0, -60.0, ]).T


In [8]:
c

array([-20., -60.])

In [9]:
A = np.array([-20.0, -60.0])

In [10]:
A*c

array([ 400., 3600.])

In [11]:
import numpy as np

x = cp.Variable(2)

c = np.array([-20.0, -60.0, ]).T

G = np.array([
    [5.0, 4.0 ],
    [2.0, 4.0],
    [2.0, 8.0],
    [-1.0, 0],
    [0, -1.0]
])

h = [80.0, 40.0, 64.0, 0.0, 0.0]

obj = cp.Minimize(c.T * x)
cons = [G*x <= h]

p = cp.Problem(obj, cons)
p.solve(verbose=True)



ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -4.814e+02  -1.107e+03  +3e+02  2e-04  3e-01  1e+00  5e+01    ---    ---    1  1  - |  -  - 
 1  -5.152e+02  -5.723e+02  +3e+01  2e-05  3e-02  3e-01  5e+00  0.9056  4e-03   0  0  0 |  0  0
 2  -5.199e+02  -5.250e+02  +3e+00  2e-06  3e-03  3e-02  4e-01  0.9101  2e-03   1  0  0 |  0  0
 3  -5.200e+02  -5.201e+02  +3e-02  2e-08  3e-05  4e-04  5e-03  0.9890  1e-04   1  0  0 |  0  0
 4  -5.200e+02  -5.200e+02  +3e-04  2e-10  4e-07  4e-06  5e-05  0.9890  1e-04   1  0  0 |  0  0
 5  -5.200e+02  -5.200e+02  +3e-06  2e-12  4e-09  5e-08  6e-07  0.9890  1e-04   1  0  0 |  0  0

OPTIMAL (within feastol=4.2e-09, reltol=6.7e-09, abstol=3.5e-06).
Runtime: 0.000160 seconds.



/home/ma/.bin/anaconda3/envs/misc/lib/python3.8/site-packages/cvxpy/expressions/expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
/home/ma/.bin/anaconda3/envs/misc/lib/python3.8/site-packages/cvxpy/expressions/expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)


-519.9999998709314

In [12]:
r = 20
np.random.seed(1)

/home/ma/.bin/anaconda3/envs/misc/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [13]:
A = np.hstack((np.random.randn(r, 1), np.ones([r,1])))


In [14]:
c = np.array(A[:,0]).T

In [15]:
c

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

In [16]:
np.random.randn(23,1)

array([[-1.10061918],
       [ 1.14472371],
       [ 0.90159072],
       [ 0.50249434],
       [ 0.90085595],
       [-0.68372786],
       [-0.12289023],
       [-0.93576943],
       [-0.26788808],
       [ 0.53035547],
       [-0.69166075],
       [-0.39675353],
       [-0.6871727 ],
       [-0.84520564],
       [-0.67124613],
       [-0.0126646 ],
       [-1.11731035],
       [ 0.2344157 ],
       [ 1.65980218],
       [ 0.74204416],
       [-0.19183555],
       [-0.88762896],
       [-0.74715829]])

In [17]:
b = (10.0*np.random.randn() *c) + (0.5+np.random.randn(r,1))



In [18]:
bb = b.T.tolist()


In [32]:
c

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

In [19]:
x = cp.Variable(2)
obj = cp.Minimize( sum(cp.square(A*x-bb)))


/home/ma/.bin/anaconda3/envs/misc/lib/python3.8/site-packages/cvxpy/expressions/expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)


ValueError: Cannot broadcast dimensions  (20,) (20, 20)